### PR TITLE
ENH: Add support for OneToOneField

### PR DESCRIPTION
**Pull request by davidastephens**

### CODE REVIEW

**Comment by postfalk** [comment]
Thank you for this pull request. I will review it as soon as possible. Are you sure that the One-to-one-field case is covered by the ForeignKey preparation? I never worked with this field type but there are some restrictions in some Django versions that makes it actually more similar to Many-to-many relationships in the sense that relations cannot be created before the item has been saved. See here https://docs.djangoproject.com/en/1.8/topics/db/examples/one_to_one/. I might one of these versions (1.8.2 or 1.8.3 to my Travis tests). Could you create a TestCase for One-to-one relationships?

**Comment by davidastephens** [comment]
Sure, I will write a test for it.  It works in my application.  

From the Django docs:

A one-to-one relationship. Conceptually, this is similar to a ForeignKey with unique=True, but the “reverse” side of the relation will directly return a single object.

Thank you for this project, it is very useful.

**Comment by postfalk** [comment]
Yes, conceptually it is the same. I just want to make sure that it works in all versions of Django.

PS: I would like to improve this project quite a bit (and finally put in PyPI). So I am very happy that someone is using it.

**Comment by davidastephens** [comment]
@postfalk Have a look at the test I added.  I copied the foreign key test.   I'm a bit new to Django and testing it, so please let me know if you have any suggestions.

**Pull request merged**
